[workspace]
members = [
    "rusty-shared-opts",
    "rusty-shared-redis",
    "rusty-shared-telegram",
    "rusty-shared-tracing",
    "rusty-shared-tractive",
    "rusty-tado",
    "rusty-tractive",
    "rusty-tractive-telegram-bot",
]
