[package]
name = "rusty-shared-tractive"
version = "0.1.0"
edition = "2021"
description = "Shared Tractive structures and functions"

[dependencies]
chrono = "0.4.19"
fred = { version = "5.1.0", default-features = false, features = ["no-client-setname"] }
kv-derive = "1.0.1"
serde = "1.0.137"
