[package]
name = "rusty-shared-opts"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.22", features = ["derive", "env"] }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
tracing = "0.1.36"
