[package]
name = "rusty-tado"
version = "0.0.0"
edition = "2021"
description = "🌡 Connects Rusty Home to tado°"

[dependencies]
anyhow = "1.0.58"
async-std = { version = "1.11.0", features = ["attributes"] }
