[package]
name = "rusty-tado"
version = "0.1.1"
edition = "2021"
description = "🌡 Connects Rusty Home to tado°"

[dependencies]
anyhow = "1.0.57"
async-std = { version = "1.11.0", features = ["attributes"] }
clap = "3.1.12"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls", "json"] }
tracing = "0.1.34"

rusty-shared-tracing = { path = "../rusty-shared-tracing" }
