[package]
name = "rusty-shared-telegram"
version = "1.0.0"
edition = "2021"
description = "Integrates Telegram Bot API"
build = "build.rs"

[dependencies]
anyhow = "1.0.57"
async-std = { version = "1.11.0" }
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls", "json"] }
serde = "1.0.136"
serde_json = "1.0.79"
serde_with = "1.13.0"
tracing = "0.1.34"

[build-dependencies]
anyhow = "*"
vergen = { version = "7", default-features = false, features = ["git"] }
