[package]
name = "rusty-shared-telegram"
version = "5.0.0"
edition = "2021"
description = "Integrates Telegram Bot API"
build = "build.rs"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
derivative = "2.2.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
serde = "1.0.136"
serde_json = "1.0.79"
serde_with = "1.13.0"
tracing = "0.1.34"

[build-dependencies]
anyhow = "*"
vergen = { version = "7", default-features = false, features = ["git"] }
