[package]
name = "rusty-shared-redis"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
fred = { version = "5.0.0", default-features = false, features = ["partial-tracing"] }
tracing = "0.1.34"
