name: Tailscale

on:
  push:
    branches:
      - main

jobs:
  tailscale:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: "1.24.2"

      - name: Show IP addresses
        run: ip addr
